export const enum ApplicationFlags {
    APPLICATION_AUTO_MODERATION_RULE_CREATE_BADGE = 64,
    GATEWAY_PRESENCE = 4096,
    GATEWAY_PRESENCE_LIMITED = 8192,
    GATEWAY_GUILD_MEMBERS = 16384,
    GATEWAY_GUILD_MEMBERS_LIMITED = 32768,
    VERIFICATION_PENDING_GUILD_LIMIT = 65536,
    EMBEDDED = 131072,
    GATEWAY_MESSAGE_CONTENT = 262144,
    GATEWAY_MESSAGE_CONTENT_LIMITED = 524288,
    APPLICATION_COMMAND_BADGE = 8388608
}

export const enum ApplicationRoleConnectionMetadataType {
    INTEGER_LESS_THAN_OR_EQUAL = 1,
    INTEGER_GREATER_THAN_OR_EQUAL,
    INTEGER_EQUAL,
    INTEGER_NOT_EQUAL,
    DATETIME_LESS_THAN_OR_EQUAL,
    DATETIME_GREATER_THAN_OR_EQUAL,
    BOOLEAN_EQUAL,
    BOOLEAN_NOT_EQUAL
}
