name: Publish Redis

on:
  workflow_dispatch:

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Setup bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Install Dependencies & Build
        run: sh ./build.sh
      # bun doesnt support methods like `-ws`, `-w or similar yet
      - name: Hop into the folder
        run: cd packages/redis
      - name: Publish Redis
      # Bun doesnt have any publish methods yet
        run: npm publish --provenance --no-git-checks --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM}}